version: '3'
services:
  database:
    image: 524528614447.dkr.ecr.us-east-2.amazonaws.com/database_sql:latest
    container_name: mysqldb
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
    - mysqlvol1:/var/lib/mysql
  Backend:
    image: 524528614447.dkr.ecr.us-east-2.amazonaws.com/backendimg:latest
    container_name: backend
    links:
    - database
  Frontend:
    image: 524528614447.dkr.ecr.us-east-2.amazonaws.com/frontendimg:latest
    container_name: frontend
    links:
    - Backend
    ports:
    - 80:80
volumes:
  mysqlvol1:
